
name: "windows kind CI workflow"

on:
  push:
    branches: [ main ]
  schedule:
      # https://crontab.guru/
      # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
      - cron:  '0 0 * * FRI' ##execution of a task in the first minute of the month  




jobs:

  windows-latest-pwsh-kind-choco:
    name: "kind choco windows-latest Microsoft Windows Server 2019 Datacenter pwsh"  
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1     
    - name: "osfingerprinting"
      run: systeminfo | more  
    - name: "check curl version"
      run: curl --version      
    - name: "install curl"
      run: choco install curl      
    # https://kind.sigs.k8s.io/docs/user/quick-start/
    - name: "Choco install kind"
      run: choco install kind
    - name: "see the list of kind clusters"
      run: kind get clusters #see the list of kind clusters



  windows-latest-pwsh-kind:
    name: "kind windows-latest Microsoft Windows Server 2019 Datacenter pwsh"  
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1     
    - name: "osfingerprinting"
      run: systeminfo | more  
    - name: "check curl version"
      run: curl --version      
    - name: "install curl"
      run: choco install curl      
    # https://kind.sigs.k8s.io/docs/user/quick-start/
    - name: "Download the kind release"
      run: |
        curl.exe -Lo kind-windows-amd64.exe https://kind.sigs.k8s.io/dl/v0.11.1/kind-windows-amd64
        New-Item -Path "c:\" -Name "kind" -ItemType "directory" -Force
        Move-Item .\kind-windows-amd64.exe c:\kind\kind.exe
        # curl -Lo minikube.exe https://github.com/kubernetes/minikube/releases/latest/download/minikube-windows-amd64.exe
        # New-Item -Path "c:\" -Name "minikube" -ItemType "directory" -Force
        # Move-Item .\minikube.exe c:\minikube\minikube.exe -Force
    - name: "see the list of kind clusters"
      run: kind get clusters #see the list of kind clusters